config/routes.rb
SchoolWatch::Application.routes.draw do
  devise_for :users

  resources :schools
  get "home/index"

  root :to => "schools#index"

end

app/models/school.rb
class School < ActiveRecord::Base

  attr_accessible :address, :code, :lat, :level, :lng, :mkt_val_2014, 
  :name, :opa, :url, :slug, :flickr_image, :flickr_image_url, :context, :street_view

  default_scope order('name ASC')

  def self.find(input)
    if input.to_i != 0
      super
    else
      find_by_slug(input)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  if Rails.env.production?
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  else
    devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable 
  end

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include ApplicationHelper

  def get_all_resources
    Rails.cache.fetch('allresources', :expires_in => 5.minutes) do 
      gsession = GoogleDrive.login(ENV["GOOGLE_DRIVE_EMAIL"], ENV["GOOGLE_DRIVE_PASSWORD"])
      sheet = gsession.spreadsheet_by_key("0AsiZZJ_cOXiMdEhTVnNGblVYTDBBU1BpQkVxQ09vdVE").worksheets[1]

      resources = gsheet_to_hash(sheet)
    end
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]
  before_filter :get_feeds, :only => [:index, :show]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
    @title = t_meta(:title)

    respond_to do |format|
      format.html do
        begin 
          @resources = get_all_resources
        rescue
          @resources = false
        end
      end
      format.json { render json: @schools }
    end
  end

  # GET /schools/slug
  # GET /schools/slug.json
  def show
    @school = School.find(params[:id])
    @title = @school.name.titleize + " | " + t_meta(:title)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  private

    def authenticate
      if !user_signed_in?
        redirect_to new_user_session_path
      end
    end

    def get_feeds
      begin
        @axp_news = RSS::Parser.parse("http://axisphilly.org/project/shuttered-school-buildings/feed/")
        @other_news = RSS::Parser.parse("http://axisphilly.org/project/shuttered-school-buildings/?feed=rss2&post_type=external_post")
        @news = combine_news(@axp_news, @other_news)
      rescue
        @news = false
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gsheet_to_hash(sheet)

    headers = sheet.rows[0]

    items = sheet.rows[1, sheet.rows.length].map { |row|
      #date = Date.strptime(row[3], '%m/%d/%Y')

      {
        headers[0].downcase => row[0],
        headers[1].downcase => row[1],
        headers[2].downcase => row[2],
        headers[3].downcase => row[3],
        headers[4].downcase => row[4]
      }
    }

    items

  end

  def t_meta_interpolation(name, hash)
    instance_variable_set("@#{name}_interpolation", hash)
  end

  def t_meta(name)
    interpolation_data = instance_variable_get("@#{name}_interpolation") || {}
    t("meta.#{controller_path.gsub("/", ".")}.#{action_name}.#{name}",
      interpolation_data.merge({ :default => t("meta.defaults.#{name}") }))
  end

  def combine_news(axis_feed, other_feed)
    combined = Array.new

    axis_feed.items.each do |story|
      combined.push({
        :url => story.link,
        :title => story.title,
        :source => 'AxisPhilly',
        :published => story.pubDate
      })
    end

    other_feed.items.each do |story|
      combined.push({
        :url => story.source.url,
        :title => story.title,
        :source => story.source.content,
        :published => story.pubDate
      })
    end

    combined.sort_by! { |k| k[:published] }.reverse!
  end

end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta property="og:site_name" content="<%=t_meta(:title)%>">
    <meta property="og:url" content="<%= request.url %>">
    <meta property="og:type" content="website">
    <meta property="og:title" content="<%=@title%>">
    <meta property="og:description" content="<%=t_meta(:description)%>">
    <meta property="og:image" content="<%=t_meta(:image_path)%>">
    <link rel="icon" href="https://s3.amazonaws.com/axisphilly-assets/images/favicon.png" type="image/x-icon" />
    <link rel="shortcut icon" href="https://s3.amazonaws.com/axisphilly-assets/images/favicon.png" type="image/x-icon" />
    <script type="text/javascript" src="//use.typekit.net/nuc2aoh.js"></script>
    <script src="https://s3.amazonaws.com/axisphilly-assets/javascripts/modernizr.foundation.js"></script>  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js" type="text/javascript"></script>
    <script src="https://s3.amazonaws.com/axisphilly-assets/javascripts/libraries.1.0.5.min.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" media="all" href="https://s3.amazonaws.com/axisphilly-assets/stylesheets/style.css" />
    <title><%= @title %> | AxisPhilly</title>
    <%= stylesheet_link_tag  "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if IE 8]>
      <%= stylesheet_link_tag 'ie', :media => 'screen' %>
    <![endif]-->
  </head>
  <body>
    <!-- Fixed header -->
    <header class="header">
        <div class="nav-container contain-to-grid">
          <nav class="top-bar">
            <ul>
              <li class="name">
                <a href="http://www.axisphilly.org"><img class="compressed-logo" alt="AxisPhilly: Where News Breaks Through" src="https://s3.amazonaws.com/axisphilly-assets/images/logo.png"/>AxisPhilly</a>
              </li>
            </ul>
            <section>
              <ul class="left">
                <li class="main-logo mtm"><a href="http://www.axisphilly.org"><img src="<%= root_url %>/images/axisphilly-logo.png"></a></li>
                <li class="menu-item"><a href="http://axisphilly.org/projects/">Our Projects</a></li>
                <li class="menu-item" ><a href="http://www.axisphilly.org/tools">Tools &amp; Data</a></li>
                <li class="menu-item"><a href="http://www.axisphilly.org/about">About</a></li>
                <li class="social"><a href="http://www.twitter.com/AxisPhilly"><i class="social-foundicon-twitter"></i></a></li>
                <li class="social"><a href="http://www.facebook.com/AxisPhilly"><i class="social-foundicon-facebook"></i></a></li>
                <li class="social"><a href="http://www.axisphilly.org/?feed=rss"><i class="social-foundicon-rss"></i></a></li>
                <% if user_signed_in? %>
                  <li><%= link_to "Logout", destroy_user_session_path %></li>
                <% end %>
              </ul>
            </section>
          </nav>
    </div>
    </header>
    <section class="row">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </section>

    <%= yield %>

    <footer>
      <div class="row colors">
        <div class="three columns mobile-one yellow"> </div>
        <div class="three columns mobile-one light-blue"> </div>
        <div class="three columns mobile-one red"> </div>
        <div class="three columns mobile-one dark-blue"> </div>
      </div>
      <div class="row about">
        <div class="three columns">
          <img class="logo" alt="AxisPhilly" src="https://s3.amazonaws.com/axisphilly-assets/images/logo-no-tagline-white.png"/>
          <p class="copyright">© 2013</p>
        </div>
        <div class="three columns">
          <ul>
            <li><a href="/about">About Us</a></li>
            <li><a href="/about/contact-us">Contact Us</a></li>
            <li><a href="/about/understanding-privacy">Privacy</a></li>
            <li><a href="/about/user-agreement/">User Agreement</a></li>
          </ul>
        </div>
        <div class="six columns">
          <section id="mc_embed_signup">
            <div class="twelve columns">
              <!-- Begin MailChimp Signup Form -->
                <form action="http://neilbudde.us4.list-manage.com/subscribe/post?u=f2095380fddf560272aa750da&amp;id=fd22697bf6" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
                  <label for="mce-EMAIL" id="email-signup-label">Sign up for email updates:</label>
                  <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required="">
                  <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
                </form>

              <!--End mc_embed_signup-->
            </div>
          </section>
        </div>
      </div>
    </footer>
    <script src="https://s3.amazonaws.com/axisphilly-assets/javascripts/foundation.min.js" type="text/javascript"></script>
    <script src="https://s3.amazonaws.com/axisphilly-assets/javascripts/site.1.0.5.min.js" type="text/javascript"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-36899552-3', 'schoolhousewatch.org');
      ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br />
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :opa %><br />
    <%= f.text_field :opa %>
  </div>
  <div class="field">
    <%= f.label :mkt_val_2014 %><br />
    <%= f.text_field :mkt_val_2014 %>
  </div>
  <div class="field">
    <%= f.label :flickr_image %><br />
    <%= f.text_field :flickr_image %>
  </div>
  <div class="field">
    <%= f.label :flickr_image_url %><br />
    <%= f.text_field :flickr_image_url %>
  </div>
  <div class="field">
    <%= f.label :street_view %><br />
    <%= f.text_field :street_view %>
  </div>
  <div class="field">
    <%= f.label :context %><br />
    <%= f.text_area :context %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schools/_news.html.erb
<div id="<%= block_id %>">
    <ul>
    <% if @news %>
      <% news.first(5).each do |story| %>
        <li class="story-item <% if story[:source] == 'AxisPhilly' %>axis-story<% end %>">
          <div>
            <%= link_to(story[:title], story[:url], :target => '_blank') %>
            <span class="source"><%= story[:source] %>, <%= story[:published].strftime('%b. %e, %Y') %></span>
          </div>
        </li>
      <% end %>
    <% else %>
      <li><em>We're having trouble retrieving updates at the moment.</em></li>
    <% end %>
    </ul>

    <p><a href="http://axisphilly.org/project/shuttered-school-buildings/">Read past coverage</a></p>
</div>

app/views/schools/_resources.html.erb
<div id="resources">
  <h6>Reference &amp; Resources</h6>
  <ul>
    <% if @resources %>
      <% @resources.each do |story| %>
        <li class="story-item">
          <div>
            <a href="<%= story['url'] %>" target="_blank"><%= story['headline'] %></a>
            <span class="source"><% if story['source'] != '' %><%= story['source'] %>, <% end %> <%= story['date'] %></span>
          </div>
        </li>
      <% end %>
    <% else %>
      <li><em>We're having trouble retrieving resources at the moment.</em></li>
    <% end %>
  </ul>
</div>

app/views/schools/edit.html.erb
<h2>Editing school</h2>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<section class="row">
  <div class="six columns main">
    <div class="main-story">
      <img class="mtl show-for-small" src="<%= root_url %>/images/homepage-school.png" />
      <h1 class="headline"><%= @title %></h1>
      <div class="byline"><span class="byline-author">by <a href="http://axisphilly.org/author/solomon/" title="Posts by Solomon Jones" rel="author">Solomon Jones</a>, <span class="byline-author"><a href="http://axisphilly.org/author/casey/" title="Posts by Casey Thomas" rel="author">Casey Thomas</a> and <a href="http://axisphilly.org/author/pam/" title="Posts by Pam Selle" rel="author">Pam Selle</a></span> <span class="byline-date">Apr. 16th, 2013. Updated Apr. 19th, 2013.</span></div>
      <p class="partner show-for-small">With editorial support by <a href="http://www.thenotebook.org" target="_blank">The Notebook</a>. In collaboration with <a href="http://www.planphilly.com">PlanPhilly</a> and <a href="http://www.nbcphiladelphia.com/">NBC10</a>.</p>

      <p>Twenty-three Philadelphia school buildings are slated to close at the end of the 2013 school year, saddling already struggling neighborhoods with more empty properties. What will ultimately happen to the school buildings?</p> 
      
      <p>This project seeks your input to help answer that question. With news stories, community events and statistics on each closing school, AxisPhilly provides a community forum where you can share your ideas on how each building can be reused.</p>

      <p>The schools that are closing this year are not the first, as the district has been downsizing for years now. In the coming weeks, SchoolHouse Watch will also be adding information about the buildings that are currently vacant, and still need solutions.
      </p>
    </div>

  <hr>
  <h6>Latest Updates</h6>
  <%= render 'news', :news => @news, :block_id => 'news' %>

  <hr>
  <%= render 'resources' %>
  </div>

  <div class="six columns sidebar">
    <div class="row hide-for-small">
      <div class="four columns">
        <p class="partner">With editorial support by:</p>
        <a href="http://thenotebook.org/" target="_blank" alt="The Public School Notebook"><img src="/images/notebook-logo.png" class="logo-fix"></a>
      </div>
      <div class="eight columns">
        <p class="partner">In collaboration with:</p>
        <a href="http://http://www.nbcphiladelphia.com/" target="_blank" alt="NBC10"><img src="/images/nbc-logo.png"></a>
        &nbsp;&nbsp;&nbsp;<a href="http://planphilly.com/" target="_blank" alt="PlanPhilly"><img src="/images/planphilly-logo.png" class="logo-fix"></a> 
      </div>
    </div>


    <img class="mtl hide-for-small" src="<%= root_url %>/images/homepage-school.png" />
    <h6 class="find-school mls">Find Your School</h6>
    <dl class="tabs">
      <dd class="active"><a href="#list">List</a></dd>
      <dd id="mapTabHeader"><a href="#map">Map</a></dd>
    </dl>
    <ul class="tabs-content">
      <li id="mapTab">
        <div id="map-div"></div>
      </li>
      <li class="active" id="listTab">
        <table class="twelve">
          <thead>
            <tr>
              <th>Name</th>
              <th>Address</th>
            </tr>
          </thead>

          <% @schools.each do |school| %>
            <tr>
              <td><%= link_to school.name.titleize, '/schools/' + school.slug %></td>
              <td><%= school.address.titleize %></td>
            </tr>
          <% end %>

        </table>
      </li>
    </ul>

    <div id="data-sources">
      <h6>Data Sources</h6>
      <p>Data was collected from the School District's <a href="http://webgui.phila.k12.pa.us/offices/a/accountability/open-data-initiative" target="_blank">Open Data Initiative</a> and <a href="http://webgui.phila.k12.pa.us/offices/f/facilities-master-plan" target="_blank">Facilities Master Plan</a>.
    </div>
  </div>
</section>
<script type="text/javascript">
app.map.run();
</script>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<section class="row">
  <div class="twelve columns">
    <ul>
      <li><a href="/">&larr; Schoolhouse Watch</a></li>
    </ul>
  </div>  
</section>

<section class="row">
  <div class="six columns main">
    <h3><%= @school.name.titleize %></h3>
    <table class="property-values">
      <tr>
        <td>
          <strong>Address</strong>
        </td>
        <td>
          <%= @school.address %>
        </td>
      </tr>
      <% if @school.url? %>
        <tr>
          <td>
            <strong>Online</strong>
          </td>
          <td>
            <%= link_to 'Website', 'http://' + @school.url %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td>
          <strong>Grade</strong>
        </td>
        <td>
          <%= @school.level.titleize %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>OPA Account</strong>
        </td>
        <td>
          <%= @school.opa %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>2014 Market Value</strong>
        </td>
        <td>
          <% if @school.mkt_val_2014 != -1 %>
            <%= number_to_currency(@school.mkt_val_2014, :precision => 0) %>
          <% else %>
            This property has not yet been reassessed under AVI.
          <% end %>
        </td>
      </tr>
    </table>
    
    <hr>
    <div id="comments" class="pull-four-mobile">
      <div class="pre-discussion">
        <span class="area-header">Discussion</span>
        <h6 class="mtn"><%= t_meta(:comment_prompt) %></h6>
      </div>
      <div id="disqus_thread"></div>
    </div>
  </div>

  <div class="six columns details-sidebar">
    <div class="hide-for-small">
      <% if @school.flickr_image_url.present? && @school.flickr_image.present?%>
        <%= link_to image_tag(@school.flickr_image_url, :width => 350), @school.flickr_image %>
      <% else %>
        <%= @school.street_view.html_safe %>
      <% end %>
    </div>

    <hr>
    
    <div>
      <div class="description">
        <% if !@school.context.nil? %>
          <%= @school.context.html_safe %>
        <% end %>
      </div>
      <h6>Latest Updates</h6>
      <%= render 'news', :news => @news, :title => 'Latest Updates', :block_id => 'latest-updates' %>
    </div>
  </div>
</section>

<script type="text/javascript">
  // Disqus stuff
  var disqus_shortname = 'axisphilly';
  var disqus_title = '<%= @title %>';
  var disqus_url = '<%= request.url %>';
  var disqus_identifier = 'axisphilly-<%= @school.name.gsub(" ", "").downcase %>';

  /* * * DON'T EDIT BELOW THIS LINE * * */
  (function() {
    var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  })();
</script>